// ./src/shared/constants/transactions/alfa-card.js
/**
 * Транзакции для счета "Альфа-Банк Карта"
 * @type {Transaction[]}
 */
export const ALFA_CARD_TRANSACTIONS = [
  {
    id: 'tx-alfa-1',
    date: '18 декабря 2025 г. в 10:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-13 100,00 ₽',
    account: 'Альфа-Банк Карта',
  },
  {
    id: 'tx-alfa-2',
    date: '10 декабря 2025 г. в 20:03',
    description: 'Перевод средств',
    category: '',
    contractor: '',
    tag: '',
    amount: '+13 100,00 ₽',
    account: 'Альфа-Банк Карта',
  },
  {
    id: 'tx-alfa-3',
    date: '10 декабря 2025 г. в 15:50',
    description: 'Снятие наличных',
    category: '',
    contractor: '',
    tag: '',
    amount: '-400,00 ₽',
    account: 'Альфа-Банк Карта',
  },
  {
    id: 'tx-alfa-4',
    date: '10 декабря 2025 г. в 15:43',
    description: 'Перевод средств',
    category: '',
    contractor: '',
    tag: '',
    amount: '+400,00 ₽',
    account: 'Альфа-Банк Карта',
  },
  {
    id: 'tx-alfa-5',
    date: '18 ноября 2025 г. в 10:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-13 100,00 ₽',
    account: 'Альфа-Банк Карта',
  },
  {
    id: 'tx-alfa-6',
    date: '10 ноября 2025 г. в 20:27',
    description: 'Перевод средств',
    category: '',
    contractor: '',
    tag: '',
    amount: '+13 100,00 ₽',
    account: 'Альфа-Банк Карта',
  },
  {
    id: 'tx-alfa-7',
    date: '18 октября 2025 г. в 10:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-13 100,00 ₽',
    account: 'Альфа-Банк Карта',
  },
  {
    id: 'tx-alfa-8',
    date: '10 октября 2025 г. в 20:16',
    description: 'Перевод средств',
    category: '',
    contractor: '',
    tag: '',
    amount: '+13 100,00 ₽',
    account: 'Альфа-Банк Карта',
  },
  {
    id: 'tx-alfa-9',
    date: '18 сентября 2025 г. в 10:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-13 100,00 ₽',
    account: 'Альфа-Банк Карта',
  },
  {
    id: 'tx-alfa-10',
    date: '8 сентября 2025 г. в 15:39',
    description: 'Перевод средств',
    category: '',
    contractor: '',
    tag: '',
    amount: '+13 100,00 ₽',
    account: 'Альфа-Банк Карта',
  },
];
