// ./src/shared/constants/transactions/cards.js
/**
 * Транзакции для папки "Наши карточки"
 * @type {Transaction[]}
 */
export const CARDS_TRANSACTIONS = [
  {
    id: 'tx-cards-1',
    date: '23 января 2026 г. в 15:35',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-4 169,48 ₽',
    account: 'HomeCredit Банк мужа',
  },
  {
    id: 'tx-cards-2',
    date: '22 января 2026 г. в 10:00',
    description: 'Подписка Premium',
    category: 'Подписки',
    contractor: 'Т-Банк',
    tag: '',
    amount: '-2 990,00 ₽',
    account: 'Т-Банк Premium',
  },
  {
    id: 'tx-cards-3',
    date: '21 января 2026 г. в 14:55',
    description: 'Оплата VPS локального VPN',
    category: 'Подписки',
    contractor: 'Reg.ru',
    tag: '',
    amount: '-1 500,00 ₽',
    account: 'Т-Банк Premium',
  },
  {
    id: 'tx-cards-4',
    date: '18 января 2026 г. в 11:00',
    description: 'Погашение ипотеки',
    category: '',
    contractor: '',
    tag: '',
    amount: '-18 881,54 ₽',
    account: 'Сбербанк жены',
  },
  {
    id: 'tx-cards-5',
    date: '18 января 2026 г. в 10:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-13 100,00 ₽',
    account: 'Альфа-Банк Карта',
  },
  {
    id: 'tx-cards-6',
    date: '18 января 2026 г. в 09:30',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-1 270,36 ₽',
    account: 'Сбербанк мужа',
  },
  {
    id: 'tx-cards-7',
    date: '17 января 2026 г. в 11:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-4 533,00 ₽',
    account: 'Газпромбанк мужа',
  },
  {
    id: 'tx-cards-8',
    date: '15 января 2026 г. в 19:00',
    description: 'OZON Premium',
    category: 'Подписки',
    contractor: '',
    tag: '',
    amount: '-199,00 ₽',
    account: 'Сбербанк мужа',
  },
  {
    id: 'tx-cards-9',
    date: '14 января 2026 г. в 11:49',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-51 470,00 ₽',
    account: 'Т-Банк Premium',
  },
  {
    id: 'tx-cards-10',
    date: '14 января 2026 г. в 11:00',
    description: 'Kaspersky Password Manager',
    category: 'Программы',
    contractor: 'Kaspersky',
    tag: '',
    amount: '-900,00 ₽',
    account: 'Т-Банк Premium',
  },
];
