// ./src/shared/constants/transactions/default.js
/**
 * @typedef {Object} Transaction
 * @property {string} id — уникальный идентификатор транзакции
 * @property {string} date — дата и время в формате 'DD MMMM YYYY г. в HH:mm'
 * @property {string} description — описание
 * @property {string} category — категория
 * @property {string} contractor — контрагент
 * @property {string} tag — тег
 * @property {string} amount — сумма с символом валюты и цветом (например, '-3,00 ₽' или '+500,00 ₽')
 * @property {string} account — название счета (для фильтрации)
 */

/**
 * Транзакции для папки "Счета" (агрегированные)
 * @type {Transaction[]}
 */
export const DEFAULT_TRANSACTIONS = [
  {
    id: 'tx-default-1',
    date: '23 января 2026 г. в 15:35',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+4 169,48 ₽',
    account: 'Совкомбанк – DevOps инженер. Нетология',
  },
  {
    id: 'tx-default-2',
    date: '23 января 2026 г. в 15:00',
    description: 'GuitarTuna Play Monthly',
    category: 'Подписки',
    contractor: 'Yousician Ltd',
    tag: '',
    amount: '-249,00 ₽',
    account: 'Apple ID',
  },
  {
    id: 'tx-default-3',
    date: '23 января 2026 г. в 09:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'МТС',
    tag: '',
    amount: '-3,00 ₽',
    account: 'МТС мужа',
  },
  {
    id: 'tx-default-4',
    date: '23 января 2026 г. в 08:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'Мегафон',
    tag: '',
    amount: '-3,00 ₽',
    account: 'Мегафон мужа',
  },
  {
    id: 'tx-default-5',
    date: '22 января 2026 г. в 20:15',
    description: 'Занятие с логопедом',
    category: 'Дошкольное развитие',
    contractor: 'Бусинка',
    tag: '',
    amount: '-800,00 ₽',
    account: 'Наличные',
  },
  {
    id: 'tx-default-6',
    date: '22 января 2026 г. в 10:00',
    description: 'Подписка Premium',
    category: 'Подписки',
    contractor: 'Т-Банк',
    tag: '',
    amount: '-2 990,00 ₽',
    account: 'Т-Банк Premium',
  },
  {
    id: 'tx-default-7',
    date: '22 января 2026 г. в 09:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'МТС',
    tag: '',
    amount: '-3,00 ₽',
    account: 'МТС мужа',
  },
  {
    id: 'tx-default-8',
    date: '22 января 2026 г. в 08:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'Мегафон',
    tag: '',
    amount: '-3,00 ₽',
    account: 'Мегафон мужа',
  },
  {
    id: 'tx-default-9',
    date: '21 января 2026 г. в 14:55',
    description: 'Оплата VPS локального VPN',
    category: 'Подписки',
    contractor: 'Reg.ru',
    tag: '',
    amount: '-1 500,00 ₽',
    account: 'Т-Банк Premium',
  },
  {
    id: 'tx-default-10',
    date: '21 января 2026 г. в 09:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'МТС',
    tag: '',
    amount: '-3,00 ₽',
    account: 'МТС мужа',
  },
  {
    id: 'tx-default-11',
    date: '21 января 2026 г. в 08:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'Мегафон',
    tag: '',
    amount: '-3,00 ₽',
    account: 'Мегафон мужа',
  },
  {
    id: 'tx-default-12',
    date: '20 января 2026 г. в 09:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'МТС',
    tag: '',
    amount: '-3,00 ₽',
    account: 'МТС мужа',
  },
  {
    id: 'tx-default-13',
    date: '20 января 2026 г. в 08:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'Мегафон',
    tag: '',
    amount: '-3,00 ₽',
    account: 'Мегафон мужа',
  },
  {
    id: 'tx-default-14',
    date: '19 января 2026 г. в 18:00',
    description: 'Занятие с логопедом',
    category: 'Дошкольное развитие',
    contractor: 'Бусинка',
    tag: '',
    amount: '-800,00 ₽',
    account: 'Наличные',
  },
  {
    id: 'tx-default-15',
    date: '19 января 2026 г. в 09:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'МТС',
    tag: '',
    amount: '-3,00 ₽',
    account: 'МТС мужа',
  },
  {
    id: 'tx-default-16',
    date: '19 января 2026 г. в 08:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'Мегафон',
    tag: '',
    amount: '-3,00 ₽',
    account: 'Мегафон мужа',
  },
  {
    id: 'tx-default-17',
    date: '18 января 2026 г. в 11:00',
    description: 'Погашение ипотеки',
    category: '',
    contractor: '',
    tag: '',
    amount: '+18 881,54 ₽',
    account: 'Сбербанк – ипотека',
  },
  {
    id: 'tx-default-18',
    date: '18 января 2026 г. в 10:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+13 100,00 ₽',
    account: 'Альфа-Банк – Кредит на кредиты',
  },
  {
    id: 'tx-default-19',
    date: '18 января 2026 г. в 09:30',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+1 270,36 ₽',
    account: 'Сбербанк – Звуковая карта и микрофон',
  },
  {
    id: 'tx-default-20',
    date: '18 января 2026 г. в 09:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'МТС',
    tag: '',
    amount: '-3,00 ₽',
    account: 'МТС мужа',
  },
  {
    id: 'tx-default-21',
    date: '18 января 2026 г. в 08:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'Мегафон',
    tag: '',
    amount: '-3,00 ₽',
    account: 'Мегафон мужа',
  },
  {
    id: 'tx-default-22',
    date: '17 января 2026 г. в 11:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+4 533,00 ₽',
    account: 'Газпромбанк – кредит на технику',
  },
  {
    id: 'tx-default-23',
    date: '17 января 2026 г. в 09:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'МТС',
    tag: '',
    amount: '-3,00 ₽',
    account: 'МТС мужа',
  },
  {
    id: 'tx-default-24',
    date: '17 января 2026 г. в 08:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'Мегафон',
    tag: '',
    amount: '-3,00 ₽',
    account: 'Мегафон мужа',
  },
  {
    id: 'tx-default-25',
    date: '16 января 2026 г. в 23:45',
    description: 'DS Manager Pro, Supporter Level',
    category: 'Инструменты разработчика',
    contractor: 'Jaroslav Pulik',
    tag: '',
    amount: '-199,00 ₽',
    account: 'Apple ID',
  },
  {
    id: 'tx-default-26',
    date: '16 января 2026 г. в 09:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'МТС',
    tag: '',
    amount: '-3,00 ₽',
    account: 'МТС мужа',
  },
  {
    id: 'tx-default-27',
    date: '16 января 2026 г. в 08:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'Мегафон',
    tag: '',
    amount: '-3,00 ₽',
    account: 'Мегафон мужа',
  },
  {
    id: 'tx-default-28',
    date: '15 января 2026 г. в 20:15',
    description: 'Занятие с логопедом',
    category: 'Дошкольное развитие',
    contractor: 'Бусинка',
    tag: '',
    amount: '-800,00 ₽',
    account: 'Наличные',
  },
  {
    id: 'tx-default-29',
    date: '15 января 2026 г. в 19:00',
    description: 'OZON Premium',
    category: 'Подписки',
    contractor: '',
    tag: '',
    amount: '-199,00 ₽',
    account: 'Сбербанк мужа',
  },
  {
    id: 'tx-default-30',
    date: '15 января 2026 г. в 09:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'МТС',
    tag: '',
    amount: '-3,00 ₽',
    account: 'МТС мужа',
  },
  {
    id: 'tx-default-31',
    date: '15 января 2026 г. в 08:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'Мегафон',
    tag: '',
    amount: '-3,00 ₽',
    account: 'Мегафон мужа',
  },
  {
    id: 'tx-default-32',
    date: '14 января 2026 г. в 11:49',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+51 470,00 ₽',
    account: 'Т-Банк Платинум – семейная кредитка',
  },
  {
    id: 'tx-default-33',
    date: '14 января 2026 г. в 11:00',
    description: 'Kaspersky Password Manager',
    category: 'Программы',
    contractor: 'Kaspersky',
    tag: '',
    amount: '-900,00 ₽',
    account: 'Т-Банк Premium',
  },
  {
    id: 'tx-default-34',
    date: '14 января 2026 г. в 10:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+934,10 ₽',
    account: 'Сбербанк – Планшет и чехол Xiaomi Pad 5',
  },
  {
    id: 'tx-default-35',
    date: '14 января 2026 г. в 09:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+229,51 ₽',
    account: 'Сбербанк – подставки планшета, датчики открытия',
  },
  {
    id: 'tx-default-36',
    date: '14 января 2026 г. в 09:00',
    description: 'Защитник',
    category: 'Услуги',
    contractor: 'МТС',
    tag: '',
    amount: '-3,00 ₽',
    account: 'МТС мужа',
  },
];
