// ./src/shared/constants/transactions/gpb-m.js
/**
 * Транзакции для счета "Газпромбанк мужа"
 * @type {Transaction[]}
 */
export const GPB_M_TRANSACTIONS = [
  {
    id: 'tx-gpb-1',
    date: '17 декабря 2025 г. в 11:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-4 533,00 ₽',
    account: 'Газпромбанк мужа',
  },
  {
    id: 'tx-gpb-2',
    date: '10 декабря 2025 г. в 20:03',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+4 543,00 ₽',
    account: 'Газпромбанк мужа',
  },
  {
    id: 'tx-gpb-3',
    date: '17 ноября 2025 г. в 11:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-4 533,00 ₽',
    account: 'Газпромбанк мужа',
  },
  {
    id: 'tx-gpb-4',
    date: '10 ноября 2025 г. в 20:27',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+4 553,00 ₽',
    account: 'Газпромбанк мужа',
  },
  {
    id: 'tx-gpb-5',
    date: '17 октября 2025 г. в 11:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-4 533,00 ₽',
    account: 'Газпромбанк мужа',
  },
  {
    id: 'tx-gpb-6',
    date: '7 октября 2025 г. в 16:45',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+3 533,00 ₽',
    account: 'Газпромбанк мужа',
  },
  {
    id: 'tx-gpb-7',
    date: '17 сентября 2025 г. в 11:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-4 533,00 ₽',
    account: 'Газпромбанк мужа',
  },
  {
    id: 'tx-gpb-8',
    date: '15 сентября 2025 г. в 16:46',
    description: 'Перевод',
    category: 'Перевод',
    contractor: 'Отец',
    tag: '',
    amount: '+1 000,00 ₽',
    account: 'Газпромбанк мужа',
  },
  {
    id: 'tx-gpb-9',
    date: '12 сентября 2025 г. в 10:36',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '-3 317,00 ₽',
    account: 'Газпромбанк мужа',
  },
  {
    id: 'tx-gpb-10',
    date: '11 сентября 2025 г. в 10:35',
    description: 'Подарок от Бабули',
    category: 'Помощь',
    contractor: 'Мама',
    tag: '',
    amount: '+5 000,00 ₽',
    account: 'Газпромбанк мужа',
  },
];
