// ./src/shared/constants/transactions/homecredit-m.js
/**
 * Транзакции для счета "HomeCredit Банк мужа"
 * @type {Transaction[]}
 */
export const HOMECREDIT_M_TRANSACTIONS = [
  {
    id: 'tx-homecredit-1',
    date: '23 января 2026 г. в 15:35',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-4 169,48 ₽',
    account: 'HomeCredit Банк мужа',
  },
  {
    id: 'tx-homecredit-2',
    date: '27 декабря 2025 г. в 15:35',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '+4 169,00 ₽',
    account: 'HomeCredit Банк мужа',
  },
  {
    id: 'tx-homecredit-3',
    date: '23 декабря 2025 г. в 09:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-4 169,48 ₽',
    account: 'HomeCredit Банк мужа',
  },
  {
    id: 'tx-homecredit-4',
    date: '10 декабря 2025 г. в 20:05',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '+4 163,00 ₽',
    account: 'HomeCredit Банк мужа',
  },
  {
    id: 'tx-homecredit-5',
    date: '23 ноября 2025 г. в 09:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-4 169,48 ₽',
    account: 'HomeCredit Банк мужа',
  },
  {
    id: 'tx-homecredit-6',
    date: '10 ноября 2025 г. в 20:28',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '+4 169,48 ₽',
    account: 'HomeCredit Банк мужа',
  },
  {
    id: 'tx-homecredit-7',
    date: '23 октября 2025 г. в 09:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-4 169,48 ₽',
    account: 'HomeCredit Банк мужа',
  },
  {
    id: 'tx-homecredit-8',
    date: '19 октября 2025 г. в 18:52',
    description: '',
    category: '',
    contractor: '',
    tag: '',
    amount: '+0,05 ₽',
    account: 'HomeCredit Банк мужа',
  },
  {
    id: 'tx-homecredit-9',
    date: '19 октября 2025 г. в 18:52',
    description: '',
    category: '',
    contractor: '',
    tag: '',
    amount: '-591,00 ₽',
    account: 'HomeCredit Банк мужа',
  },
  {
    id: 'tx-homecredit-10',
    date: '4 октября 2025 г. в 17:15',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '+3 864,00 ₽',
    account: 'HomeCredit Банк мужа',
  },
];
