// ./src/shared/constants/transactions/mts-m.js
/**
 * Транзакции для счета "МТС банк мужа"
 * @type {Transaction[]}
 */
export const MTS_M_TRANSACTIONS = [
  {
    id: 'tx-mts-1',
    date: '27 ноября 2025 г. в 11:34',
    description: '',
    category: '',
    contractor: '',
    tag: '',
    amount: '-1 150,00 ₽',
    account: 'МТС банк мужа',
  },
  {
    id: 'tx-mts-2',
    date: '4 сентября 2025 г. в 08:27',
    description: 'Пополнение баланса',
    category: '',
    contractor: '',
    tag: '',
    amount: '-3 000,00 ₽',
    account: 'МТС банк мужа',
  },
  {
    id: 'tx-mts-3',
    date: '4 сентября 2025 г. в 08:27',
    description: 'Пополнение баланса',
    category: '',
    contractor: '',
    tag: '',
    amount: '+2 800,00 ₽',
    account: 'МТС банк мужа',
  },
  {
    id: 'tx-mts-4',
    date: '28 августа 2025 г. в 23:00',
    description: 'Пополнение баланса',
    category: '',
    contractor: '',
    tag: '',
    amount: '+1 350,00 ₽',
    account: 'МТС банк мужа',
  },
  {
    id: 'tx-mts-5',
    date: '14 апреля 2025 г. в 07:23',
    description: 'Полное досрочное погашение',
    category: '',
    contractor: '',
    tag: '',
    amount: '-4 233,48 ₽',
    account: 'МТС банк мужа',
  },
  {
    id: 'tx-mts-6',
    date: '13 апреля 2025 г. в 13:47',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+3 157,48 ₽',
    account: 'МТС банк мужа',
  },
  {
    id: 'tx-mts-7',
    date: '10 апреля 2025 г. в 22:47',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+1 076,00 ₽',
    account: 'МТС банк мужа',
  },
  {
    id: 'tx-mts-8',
    date: '21 марта 2025 г. в 16:03',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-1 076,00 ₽',
    account: 'МТС банк мужа',
  },
  {
    id: 'tx-mts-9',
    date: '10 марта 2025 г. в 22:06',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+1 076,00 ₽',
    account: 'МТС банк мужа',
  },
  {
    id: 'tx-mts-10',
    date: '21 февраля 2025 г. в 16:03',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-1 076,00 ₽',
    account: 'МТС банк мужа',
  },
];
