// ./src/shared/constants/transactions/ozon.js
/**
 * Транзакции для счета "OZON карта"
 * @type {Transaction[]}
 */
export const OZON_TRANSACTIONS = [
  {
    id: 'tx-ozon-1',
    date: '1 сентября 2025 г. в 10:02',
    description: 'Аппликатор дозатор для флюса с кистью BON-102',
    category: 'Startup',
    contractor: 'OZON',
    tag: '',
    amount: '-282,59 ₽',
    account: 'OZON карта',
  },
  {
    id: 'tx-ozon-2',
    date: '1 сентября 2025 г. в 10:02',
    description: 'Держатель для пайки проводов третья рука',
    category: 'Startup',
    contractor: 'OZON',
    tag: '',
    amount: '-151,28 ₽',
    account: 'OZON карта',
  },
  {
    id: 'tx-ozon-3',
    date: '1 сентября 2025 г. в 10:02',
    description:
      '2 метра Кабель Micro USB/ кабель микро iOS5 для телефона/ EMYX',
    category: 'Покупки',
    contractor: 'OZON',
    tag: '',
    amount: '-498,00 ₽',
    account: 'OZON карта',
  },
  {
    id: 'tx-ozon-4',
    date: '1 сентября 2025 г. в 10:02',
    description: 'Обработка заказа в пункте выдачи',
    category: 'Startup',
    contractor: 'OZON',
    tag: '',
    amount: '-29,36 ₽',
    account: 'OZON карта',
  },
  {
    id: 'tx-ozon-5',
    date: '1 сентября 2025 г. в 10:02',
    description: 'Губка для очистки жала паяльника комплект 5 спонжей',
    category: 'Startup',
    contractor: 'OZON',
    tag: '',
    amount: '-141,77 ₽',
    account: 'OZON карта',
  },
  {
    id: 'tx-ozon-6',
    date: '1 сентября 2025 г. в 10:01',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '+10,00 ₽',
    account: 'OZON карта',
  },
  {
    id: 'tx-ozon-7',
    date: '1 сентября 2025 г. в 10:01',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '+12,00 ₽',
    account: 'OZON карта',
  },
  {
    id: 'tx-ozon-8',
    date: '1 сентября 2025 г. в 10:00',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '+485,00 ₽',
    account: 'OZON карта',
  },
  {
    id: 'tx-ozon-9',
    date: '26 августа 2025 г. в 11:23',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '+605,00 ₽',
    account: 'OZON карта',
  },
  {
    id: 'tx-ozon-10',
    date: '21 августа 2025 г. в 16:16',
    description: '?',
    category: 'Startup',
    contractor: 'OZON',
    tag: '',
    amount: '+1 098,24 ₽',
    account: 'OZON карта',
  },
];
