// ./src/shared/constants/transactions/pochtabank-debit-m.js
/**
 * Транзакции для счета "ПочтаБанк - дебетовая карта мужа"
 * @type {Transaction[]}
 */
export const POCHTABANK_DEBIT_M_TRANSACTIONS = [
  {
    id: 'tx-pochta-1',
    date: '27 декабря 2025 г. в 15:29',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+5 044,00 ₽',
    account: 'ПочтаБанк - дебетовая карта мужа',
  },
  {
    id: 'tx-pochta-2',
    date: '10 декабря 2025 г. в 20:03',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-5 044,00 ₽',
    account: 'ПочтаБанк - дебетовая карта мужа',
  },
  {
    id: 'tx-pochta-3',
    date: '10 декабря 2025 г. в 20:02',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+5 044,00 ₽',
    account: 'ПочтаБанк - дебетовая карта мужа',
  },
  {
    id: 'tx-pochta-4',
    date: '12 ноября 2025 г. в 09:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-5 044,00 ₽',
    account: 'ПочтаБанк - дебетовая карта мужа',
  },
  {
    id: 'tx-pochta-5',
    date: '10 ноября 2025 г. в 20:24',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+5 044,00 ₽',
    account: 'ПочтаБанк - дебетовая карта мужа',
  },
  {
    id: 'tx-pochta-6',
    date: '12 октября 2025 г. в 09:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-5 044,00 ₽',
    account: 'ПочтаБанк - дебетовая карта мужа',
  },
  {
    id: 'tx-pochta-7',
    date: '7 октября 2025 г. в 16:42',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+5 044,00 ₽',
    account: 'ПочтаБанк - дебетовая карта мужа',
  },
  {
    id: 'tx-pochta-8',
    date: '12 сентября 2025 г. в 09:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-5 044,00 ₽',
    account: 'ПочтаБанк - дебетовая карта мужа',
  },
  {
    id: 'tx-pochta-9',
    date: '26 августа 2025 г. в 08:23',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '+5 044,00 ₽',
    account: 'ПочтаБанк - дебетовая карта мужа',
  },
  {
    id: 'tx-pochta-10',
    date: '12 августа 2025 г. в 09:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-5 044,00 ₽',
    account: 'ПочтаБанк - дебетовая карта мужа',
  },
];
