// ./src/shared/constants/transactions/sber-m.js
/**
 * Транзакции для счета "Сбербанк мужа"
 * @type {Transaction[]}
 */
export const SBER_M_TRANSACTIONS = [
  {
    id: 'tx-sber-m-1',
    date: '6 января 2026 г. в 15:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-3 100,00 ₽',
    account: 'Сбербанк мужа',
  },
  {
    id: 'tx-sber-m-2',
    date: '2 января 2026 г. в 16:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-371,40 ₽',
    account: 'Сбербанк мужа',
  },
  {
    id: 'tx-sber-m-3',
    date: '27 декабря 2025 г. в 15:21',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '-1,00 ₽',
    account: 'Сбербанк мужа',
  },
  {
    id: 'tx-sber-m-4',
    date: '27 декабря 2025 г. в 15:20',
    description: 'Погашение кредитов',
    category: '',
    contractor: '',
    tag: '',
    amount: '+300,00 ₽',
    account: 'Сбербанк мужа',
  },
  {
    id: 'tx-sber-m-5',
    date: '27 декабря 2025 г. в 15:19',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '-3 800,00 ₽',
    account: 'Сбербанк мужа',
  },
  {
    id: 'tx-sber-m-6',
    date: '27 декабря 2025 г. в 15:13',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '-9 590,00 ₽',
    account: 'Сбербанк мужа',
  },
  {
    id: 'tx-sber-m-7',
    date: '26 декабря 2025 г. в 11:19',
    description: 'Подписка плюс',
    category: 'Подписки',
    contractor: 'Яндекс',
    tag: '',
    amount: '-299,00 ₽',
    account: 'Сбербанк мужа',
  },
  {
    id: 'tx-sber-m-8',
    date: '26 декабря 2025 г. в 10:58',
    description: 'Перевод на сбербанк мужа 2',
    category: '',
    contractor: '',
    tag: '',
    amount: '+23 000,00 ₽',
    account: 'Сбербанк мужа',
  },
  {
    id: 'tx-sber-m-9',
    date: '16 декабря 2025 г. в 10:00',
    description: 'Тариф Премиум',
    category: 'Программы',
    contractor: 'Яндекс 360',
    tag: '',
    amount: '-2 290,00 ₽',
    account: 'Сбербанк мужа',
  },
  {
    id: 'tx-sber-m-10',
    date: '13 декабря 2025 г. в 20:18',
    description: 'Комиссия банка',
    category: 'Комиссия',
    contractor: 'Сбербанк',
    tag: '',
    amount: '-50,00 ₽',
    account: 'Сбербанк мужа',
  },
];
