// ./src/shared/constants/transactions/sber-w.js
/**
 * Транзакции для счета "Сбербанк жены"
 * @type {Transaction[]}
 */
export const SBER_W_TRANSACTIONS = [
  {
    id: 'tx-sber-w-1',
    date: '4 января 2026 г. в 22:26',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '-865,00 ₽',
    account: 'Сбербанк жены',
  },
  {
    id: 'tx-sber-w-2',
    date: '29 декабря 2025 г. в 22:25',
    description: 'Помощь',
    category: 'Помощь',
    contractor: 'Владимир Иванович',
    tag: '',
    amount: '-300,00 ₽',
    account: 'Сбербанк жены',
  },
  {
    id: 'tx-sber-w-3',
    date: '18 декабря 2025 г. в 11:00',
    description: 'Погашение ипотеки',
    category: '',
    contractor: '',
    tag: '',
    amount: '-18 881,54 ₽',
    account: 'Сбербанк жены',
  },
  {
    id: 'tx-sber-w-4',
    date: '10 декабря 2025 г. в 20:02',
    description: 'На ипотеку',
    category: '',
    contractor: '',
    tag: '',
    amount: '+19 000,00 ₽',
    account: 'Сбербанк жены',
  },
  {
    id: 'tx-sber-w-5',
    date: '5 декабря 2025 г. в 15:00',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '-279,00 ₽',
    account: 'Сбербанк жены',
  },
  {
    id: 'tx-sber-w-6',
    date: '18 ноября 2025 г. в 11:00',
    description: 'Погашение ипотеки',
    category: '',
    contractor: '',
    tag: '',
    amount: '-18 881,54 ₽',
    account: 'Сбербанк жены',
  },
  {
    id: 'tx-sber-w-7',
    date: '17 ноября 2025 г. в 16:32',
    description: 'Помощь',
    category: '',
    contractor: '',
    tag: '',
    amount: '+0,60 ₽',
    account: 'Сбербанк жены',
  },
  {
    id: 'tx-sber-w-8',
    date: '15 ноября 2025 г. в 16:47',
    description: 'Помощь',
    category: 'Помощь',
    contractor: 'Владимир Иванович',
    tag: '',
    amount: '-200,00 ₽',
    account: 'Сбербанк жены',
  },
  {
    id: 'tx-sber-w-9',
    date: '11 ноября 2025 г. в 11:04',
    description: 'Дочке на детсад',
    category: '',
    contractor: '',
    tag: '',
    amount: '+2 000,00 ₽',
    account: 'Сбербанк жены',
  },
  {
    id: 'tx-sber-w-10',
    date: '10 ноября 2025 г. в 20:27',
    description: 'На ипотеку',
    category: '',
    contractor: '',
    tag: '',
    amount: '+19 000,00 ₽',
    account: 'Сбербанк жены',
  },
];
