// ./src/shared/constants/transactions/sber-w-mir.js
/**
 * Транзакции для счета "Сбербанк Жены МИР"
 * @type {Transaction[]}
 */
export const SBER_W_MIR_TRANSACTIONS = [
  {
    id: 'tx-sber-w-mir-1',
    date: '28 июля 2024 г. в 10:32',
    description: 'Покупки',
    category: 'Покупки',
    contractor: '',
    tag: '',
    amount: '-41,07 ₽',
    account: 'Сбербанк Жены МИР',
  },
  {
    id: 'tx-sber-w-mir-2',
    date: '12 июня 2024 г. в 00:40',
    description: 'Помощь',
    category: 'Перевод',
    contractor: 'Владимир Иванович',
    tag: '',
    amount: '-200,00 ₽',
    account: 'Сбербанк Жены МИР',
  },
  {
    id: 'tx-sber-w-mir-3',
    date: '8 июня 2024 г. в 13:31',
    description: 'Помощь',
    category: 'Перевод',
    contractor: 'Владимир Иванович',
    tag: '',
    amount: '-200,00 ₽',
    account: 'Сбербанк Жены МИР',
  },
  {
    id: 'tx-sber-w-mir-4',
    date: '7 июня 2024 г. в 12:40',
    description: 'Лекарства',
    category: 'Лекарства',
    contractor: 'Аптека Вита',
    tag: '',
    amount: '-139,00 ₽',
    account: 'Сбербанк Жены МИР',
  },
  {
    id: 'tx-sber-w-mir-5',
    date: '7 июня 2024 г. в 00:42',
    description: 'Перевод средств',
    category: '',
    contractor: '',
    tag: '',
    amount: '+100,00 ₽',
    account: 'Сбербанк Жены МИР',
  },
  {
    id: 'tx-sber-w-mir-6',
    date: '7 июня 2024 г. в 00:41',
    description: 'Перевод средств',
    category: '',
    contractor: '',
    tag: '',
    amount: '+400,00 ₽',
    account: 'Сбербанк Жены МИР',
  },
  {
    id: 'tx-sber-w-mir-7',
    date: '30 мая 2024 г. в 14:20',
    description: 'Доктор Мом, сироп 150 мл N20 таб',
    category: 'От боли в горле',
    contractor: 'Фармаленд',
    tag: '',
    amount: '-349,10 ₽',
    account: 'Сбербанк Жены МИР',
  },
  {
    id: 'tx-sber-w-mir-8',
    date: '30 мая 2024 г. в 14:20',
    description: 'Ангидак 0.255 мг / доза 30 мл',
    category: 'От боли в горле',
    contractor: 'Фармаленд',
    tag: '',
    amount: '-391,08 ₽',
    account: 'Сбербанк Жены МИР',
  },
  {
    id: 'tx-sber-w-mir-9',
    date: '30 мая 2024 г. в 14:20',
    description: 'Римантадин 50 мг N20 таб',
    category: 'Противовирусные препараты',
    contractor: 'Фармаленд',
    tag: '',
    amount: '-148,50 ₽',
    account: 'Сбербанк Жены МИР',
  },
  {
    id: 'tx-sber-w-mir-10',
    date: '30 мая 2024 г. в 14:20',
    description: 'Римантадин 50 мг N20 таб',
    category: 'Противовирусные препараты',
    contractor: 'Фармаленд',
    tag: '',
    amount: '-148,50 ₽',
    account: 'Сбербанк Жены МИР',
  },
];
