// ./src/shared/constants/transactions/sber-m2.js
/**
 * Транзакции для счета "Сбербанк мужа 2"
 * @type {Transaction[]}
 */
export const SBER_M2_TRANSACTIONS = [
  {
    id: 'tx-sber-m2-1',
    date: '7 января 2026 г. в 10:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-503,70 ₽',
    account: 'Сбербанк мужа 2',
  },
  {
    id: 'tx-sber-m2-2',
    date: '7 января 2026 г. в 10:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-356,57 ₽',
    account: 'Сбербанк мужа 2',
  },
  {
    id: 'tx-sber-m2-3',
    date: '7 января 2026 г. в 10:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-755,38 ₽',
    account: 'Сбербанк мужа 2',
  },
  {
    id: 'tx-sber-m2-4',
    date: '4 января 2026 г. в 10:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-1 139,12 ₽',
    account: 'Сбербанк мужа 2',
  },
  {
    id: 'tx-sber-m2-5',
    date: '2 января 2026 г. в 10:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-325,82 ₽',
    account: 'Сбербанк мужа 2',
  },
  {
    id: 'tx-sber-m2-6',
    date: '29 декабря 2025 г. в 10:00',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-11 640,30 ₽',
    account: 'Сбербанк мужа 2',
  },
  {
    id: 'tx-sber-m2-7',
    date: '27 декабря 2025 г. в 15:21',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '+1,00 ₽',
    account: 'Сбербанк мужа 2',
  },
  {
    id: 'tx-sber-m2-8',
    date: '27 декабря 2025 г. в 15:19',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '+3 800,00 ₽',
    account: 'Сбербанк мужа 2',
  },
  {
    id: 'tx-sber-m2-9',
    date: '27 декабря 2025 г. в 15:13',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '+9 590,00 ₽',
    account: 'Сбербанк мужа 2',
  },
  {
    id: 'tx-sber-m2-10',
    date: '27 декабря 2025 г. в 15:12',
    description: 'Погашение кредитов',
    category: '',
    contractor: '',
    tag: '',
    amount: '+2 600,00 ₽',
    account: 'Сбербанк мужа 2',
  },
];
