// ./src/shared/constants/transactions/tbank-premium.js
/**
 * Транзакции для счета "T-Банк Premium"
 * @type {Transaction[]}
 */
export const TBank_Premium_TRANSACTIONS = [
  {
    id: 'tx-tbank-1',
    date: '6 января 2026 г. в 17:20',
    description: 'Premier',
    category: 'Подписки',
    contractor: 'RUTUBE',
    tag: '',
    amount: '-49,00 ₽',
    account: 'T-Банк Premium',
  },
  {
    id: 'tx-tbank-2',
    date: '3 января 2026 г. в 18:51',
    description: 'Алиса ПРО',
    category: 'Подписки',
    contractor: 'Яндекс',
    tag: '',
    amount: '-100,00 ₽',
    account: 'T-Банк Premium',
  },
  {
    id: 'tx-tbank-3',
    date: '30 декабря 2025 г. в 21:08',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '-100 000,00 ₽',
    account: 'T-Банк Premium',
  },
  {
    id: 'tx-tbank-4',
    date: '30 декабря 2025 г. в 21:06',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '-100 000,00 ₽',
    account: 'T-Банк Premium',
  },
  {
    id: 'tx-tbank-5',
    date: '30 декабря 2025 г. в 19:37',
    description:
      'Расчет при увольнении по трудовому договору за декабрь 2025 согласно реестру зачислений № 1605 от 30.12.2025. НДС не предусмотрен.',
    category: 'Зарплата',
    contractor: 'Osinit',
    tag: '',
    amount: '+238 169,11 ₽',
    account: 'T-Банк Premium',
  },
  {
    id: 'tx-tbank-6',
    date: '30 декабря 2025 г. в 18:44',
    description: 'Снятие наличных',
    category: '',
    contractor: '',
    tag: '',
    amount: '-5 000,00 ₽',
    account: 'T-Банк Premium',
  },
  {
    id: 'tx-tbank-7',
    date: '30 декабря 2025 г. в 17:03',
    description: 'Перевод между счетами',
    category: '',
    contractor: '',
    tag: '',
    amount: '-300,00 ₽',
    account: 'T-Банк Premium',
  },
  {
    id: 'tx-tbank-8',
    date: '27 декабря 2025 г. в 16:58',
    description: 'VPS облачный сервер',
    category: 'Инструменты разработчика',
    contractor: 'Timeweb',
    tag: '',
    amount: '-1 200,00 ₽',
    account: 'T-Банк Premium',
  },
  {
    id: 'tx-tbank-9',
    date: '27 декабря 2025 г. в 15:49',
    description: 'Пополнение баланса',
    category: '',
    contractor: '',
    tag: '',
    amount: '-600,00 ₽',
    account: 'T-Банк Premium',
  },
  {
    id: 'tx-tbank-10',
    date: '27 декабря 2025 г. в 15:41',
    description: 'Погашение кредита',
    category: '',
    contractor: '',
    tag: '',
    amount: '-9 249,36 ₽',
    account: 'T-Банк Premium',
  },
];
